<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IP-C6134807" ignored="2" name="AmbrosiaTest" tests="4" failures="0" timestamp="28 Aug 2019 09:17:58 GMT" time="64.808" errors="0">
  <testcase name="@AfterTest collectEventDetails" time="0.148" classname="com.abrosia.zest.testcases.EventNavigation">
    <failure type="java.lang.RuntimeException" message="Unexpected result for screenshot command: null">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: null
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:304)
at com.abrosia.zest.utils.POMFunction.TakeScreenShot(POMFunction.java:141)
at com.abrosia.zest.testcases.EventNavigation.collectEventDetails(EventNavigation.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterTest collectEventDetails -->
  <testcase name="clickEvent" time="30.566" classname="com.abrosia.zest.testcases.EventNavigation"/>
  <testcase name="AmbrosiaLogin" time="4.316" classname="com.abrosia.zest.testcases.LaunchAmbrosia"/>
  <testcase name="selectEventRandomly" time="30.474" classname="com.abrosia.zest.testcases.EventNavigation"/>
  <testcase name="LoginValidation" time="0.08" classname="com.abrosia.zest.testcases.LaunchAmbrosia"/>
  <testcase name="GrabbedAllTableData" time="0.0" classname="com.abrosia.zest.testcases.LaunchAmbrosia">
    <ignored/>
  </testcase> <!-- GrabbedAllTableData -->
  <testcase name="OpenSelectedReport" time="0.0" classname="com.abrosia.zest.testcases.LaunchAmbrosia">
    <ignored/>
  </testcase> <!-- OpenSelectedReport -->
</testsuite> <!-- AmbrosiaTest -->
